"use client";
import { useEffect, useMemo, useState } from "react";
import { Plus, Target, Trophy, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
type EventKey="12"|"20"|"28"|"410"|"doubles"; type Score={event:EventKey;broken:number;targets:number}; type Shoot={id:number;shootNumber:number|null;name:string;date:string;scores:Score[]};
const eventInfo:Record<EventKey,{label:string;short:string;thresholds:[string,number][]}>={"12":{label:"12 Gauge",short:"12",thresholds:[["AAA",.985],["AA",.975],["A",.96],["B",.935],["C",.9],["D",.855],["E",0]]},"20":{label:"20 Gauge",short:"20",thresholds:[["AAA",.9825],["AA",.97],["A",.945],["B",.91],["C",.855],["D",0]]},"28":{label:"28 Gauge",short:"28",thresholds:[["AAA",.98],["AA",.965],["A",.94],["B",.905],["C",.855],["D",0]]},"410":{label:".410 Bore",short:".410",thresholds:[["AAA",.965],["AA",.945],["A",.91],["B",.86],["C",.8],["D",0]]},doubles:{label:"Doubles",short:"DBLS",thresholds:[["AAA",.97],["AA",.95],["A",.91],["B",.85],["C",.8],["D",0]]}};
const keys=Object.keys(eventInfo) as EventKey[]; const hoa4:[string,number][]=[["AAA",.9781],["AA",.9638],["A",.9388],["B",.9025],["C",.8525],["D",.7925],["E",0]],hoa5:[string,number][]=[["AAA",.9764],["AA",.961],["A",.933],["B",.892],["C",.842],["D",.782],["E",0]];
const classify=(avg:number,t:[string,number][])=>t.find(([,floor])=>avg>=floor)?.[0]??"—"; const fmt=(n:number)=>n.toFixed(4).replace(/^0/,"");
export default function Home(){const [shoots,setShoots]=useState<Shoot[]>([]),[loading,setLoading]=useState(true),[showForm,setShowForm]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");const [form,setForm]=useState({name:"",date:"",scores:{"12":"","20":"","28":"","410":"",doubles:""} as Record<EventKey,string>});
 const load=()=>fetch("/api/shoots").then(r=>r.json()).then(d=>{if(d.error)throw new Error(d.error);setShoots(d.shoots)}).catch(e=>setError(e.message)).finally(()=>setLoading(false)); useEffect(load,[]);
 const stats=useMemo(()=>Object.fromEntries(keys.map(key=>{const active=shoots.flatMap(s=>s.scores.filter(x=>x.event===key).map(x=>({...x,date:s.date,name:s.name}))).slice(-5);const broken=active.reduce((a,x)=>a+x.broken,0),targets=active.reduce((a,x)=>a+x.targets,0),average=targets?broken/targets:0;return[key,{active,average,className:classify(average,eventInfo[key].thresholds)}]})) as Record<EventKey,{active:(Score&{date:string;name:string})[];average:number;className:string}>,[shoots]);
 const hoa=(stats["12"].average+stats["20"].average+stats["28"].average+stats["410"].average)/4,haa=(hoa*4+stats.doubles.average)/5;
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{const scores=Object.fromEntries(keys.map(k=>[k,form.scores[k]===""?null:Number(form.scores[k])]));const r=await fetch("/api/shoots",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:form.name,date:form.date,scores})});const d=await r.json();if(!r.ok)throw new Error(d.error);setForm({name:"",date:"",scores:{"12":"","20":"","28":"","410":"",doubles:""}});setShowForm(false);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save")}finally{setSaving(false)}}
 return <main><header><div><p className="eyebrow">NSSA MEMBER 309049</p><h1>Skeet record</h1><p className="sub">James Delosh · 2026 shooting year</p></div><Button onClick={()=>setShowForm(!showForm)} className="add"><Plus/> Add shoot</Button></header>{error&&<div className="error">{error}</div>}
 {showForm&&<form className="entry" onSubmit={submit}><div className="entry-head"><div><h2>New registered shoot</h2><p>Leave an event blank if you did not shoot it.</p></div><button type="button" aria-label="Close" onClick={()=>setShowForm(false)}><X/></button></div><div className="form-grid"><label>Shoot name<Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Date<Input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label></div><div className="scores">{keys.map(k=><label key={k}>{eventInfo[k].short}<Input min="0" max="100" type="number" placeholder="—" value={form.scores[k]} onChange={e=>setForm({...form,scores:{...form.scores,[k]:e.target.value}})}/></label>)}</div><Button disabled={saving}>{saving?"Saving…":"Save shoot"}</Button></form>}
 <section className="overview"><div className="overall"><span><Trophy/> HOA</span><strong>{loading?"—":fmt(hoa)}</strong><b>{loading?"—":classify(hoa,hoa4)}</b><small>4-gun</small></div><div className="overall"><span><Trophy/> HAA</span><strong>{loading?"—":fmt(haa)}</strong><b>{loading?"—":classify(haa,hoa5)}</b><small>5-gun</small></div></section>
 <section className="event-grid">{keys.map(k=>{const s=stats[k];return <article className="event-card" key={k}><div className="event-top"><div><p>{eventInfo[k].label}</p><strong>{loading?"—":fmt(s.average)}</strong></div><span>{loading?"—":s.className}</span></div><div className="five">{s.active.map((x,i)=><div key={i} title={x.name}><b>{x.broken}</b><small>{new Date(x.date+"T12:00:00").toLocaleDateString("en-US",{month:"short",year:"2-digit"})}</small></div>)}</div><p className="count">Last {s.active.length} registered events</p></article>})}</section>
 <section className="history"><div className="section-title"><div><p className="eyebrow">TOURNAMENT HISTORY</p><h2>{shoots.length} registered shoots</h2></div><Target/></div><Table><TableHeader><TableRow><TableHead>Date / shoot</TableHead>{keys.map(k=><TableHead key={k}>{eventInfo[k].short}</TableHead>)}</TableRow></TableHeader><TableBody>{[...shoots].reverse().map(s=><TableRow key={s.id}><TableCell><strong>{new Date(s.date+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}</strong><span>{s.name}</span></TableCell>{keys.map(k=><TableCell key={k}>{s.scores.find(x=>x.event===k)?.broken??"—"}</TableCell>)}</TableRow>)}</TableBody></Table></section><footer>Classes calculated with the 2026 NSSA Universal Classification Tables.</footer></main>}
